import Head from 'next/head'
import { Layout } from '../component/Layout/MainLayout'
import Characters from './characters'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Characters />
      </Layout>
    </div>
  )
}
